# Generated by Django 5.0.5 on 2024-05-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='email',
            field=models.EmailField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='endereco',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='idade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='quarto',
            field=models.CharField(choices=[('SOLTEIRO', 'Solteiro'), ('CASAL', 'Casal'), ('CONFORTO', 'Conforto'), ('LUXO', 'Luxo')], default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserva',
            name='sobrenome',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
