# Generated by Django 5.0.5 on 2024-05-16 14:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_reserva_email_reserva_endereco_reserva_idade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
