# Generated by Django 5.0.5 on 2024-05-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_reserva_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel',
            field=models.ImageField(default=0, upload_to='foto_hotel/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='descricao',
            field=models.TextField(max_length=1800),
        ),
    ]
