# Generated by Django 5.0.5 on 2024-05-16 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_hotel_hotel_alter_hotel_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel',
        ),
    ]
