# Generated by Django 5.0.5 on 2024-05-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_remove_hotel_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='foto_hotel',
            field=models.ImageField(default=0, upload_to='foto_hotel/'),
            preserve_default=False,
        ),
    ]
